language: generic
notifications:
  email: false
script:
- :
before_deploy:
- cd src
deploy:
  skip_cleanup: true
  provider: s3
  bucket: com.is-quarantine-over-yet
  access_key_id: AKIA2CQO232KIMMZ5LD3
